# Generated by Django 5.1.6 on 2025-02-28 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharactersModel',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_language', models.CharField(max_length=255)),
                ('dialog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoriesModel',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PeoplesModel',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(choices=[('london', 'London'), ('loughborough', 'Loughborough'), ('coventry', 'Coventry'), ('derby', 'Derby')], max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentsModel',
            fields=[
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.storiesmodel')),
                ('incident_what', models.TextField()),
                ('incident_where', models.CharField(max_length=255)),
                ('incident_when', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='storiesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('media_url', models.SlugField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PointsModel',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptsModel',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StoryCharactersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.charactersmodel')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StoryLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linksmodel')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VAKSModel',
            fields=[
                ('vaks_id', models.AutoField(primary_key=True, serialize=False)),
                ('sight', models.TextField()),
                ('height', models.TextField()),
                ('smell', models.TextField()),
                ('taste', models.TextField()),
                ('touch', models.TextField()),
                ('emotion', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleIncidentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.peoplesmodel')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incidentsmodel')),
            ],
            options={
                'unique_together': {('person', 'incident')},
            },
        ),
    ]
