# Generated by Django 5.1.6 on 2025-02-24 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tasksmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharactersModel',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_language', models.CharField(max_length=255)),
                ('dialog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IncidentsModel',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_what', models.TextField()),
                ('incident_where', models.CharField(max_length=255)),
                ('incident_when', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PeoplesModel',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='usersmodel',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usersmodel',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='city',
            field=models.CharField(choices=[('london', 'London'), ('loughborough', 'Loughborough'), ('coventry', 'Coventry'), ('derby', 'Derby')], max_length=100),
        ),
        migrations.CreateModel(
            name='PeopleIncidentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incidentsmodel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.peoplesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StoriesModel',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptsModel',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PointsModel',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('media_url', models.SlugField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.AddField(
            model_name='incidentsmodel',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel'),
        ),
        migrations.CreateModel(
            name='StoryCharactersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.charactersmodel')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StoryLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linksmodel')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VAKSModel',
            fields=[
                ('vaks_id', models.AutoField(primary_key=True, serialize=False)),
                ('sight', models.TextField()),
                ('height', models.TextField()),
                ('smell', models.TextField()),
                ('taste', models.TextField()),
                ('touch', models.TextField()),
                ('emotion', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storiesmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='TasksModel',
        ),
    ]
