# Generated by Django 5.1.6 on 2025-03-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_characters_storycharactersmodel_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaModel',
        ),
    ]
